### ISSUE TITLE
API Overhaul

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipld-format#23]
* [ ] #8 Extract DAGService and friends
    * [ ] Get a review on the last few commits
    * [ ] Get a final sign off.
    * [ ] Merge it!
* [ ] Fix all the other IPLD Node API issues all at once (annother PR)
    * [ ] #9 Remove the Link structure, it's DagProtobuf specific
    * [ ] #12 Remove the Size method
    * [ ] #10 Remove the Copy method
    * [ ] #11 Remove the Stat method
* [ ] Update all other IPLD implementations to use the now fixed IPLD Node API.
* [ ] Update go-ipfs all at once.

I originally planned on doing this in stages but I'm now of the opinion that breaking everything all at once will be much less painful (it will still be very painful...).

**Comment by Stebalien** [comment]
cc @kevina, @whyrusleeping, @Kubuxu

**Comment by kevina** [comment]
@Stebalien I don't have any problems the idea but I would need to see more of the implementation before I can provide any useful feedback.

**Comment by warpfork** [comment]
I just clicked a bunch of checkmarks in here because it to me like some of the referenced issues have been merged :)

**Comment by Stebalien** [comment]
Yeah, just not the other ones "like making dag nodes behave".
